### ISSUE TITLE
ALAMODE for low dimensional materials 

### ISSUE THREAD

**Issue by zhibingao** [ttadano/alamode#10]
Dear Tadano,

Is there any possibility to set a uniform kmesh for thermal conductivity like:
&kpoint
  2  # KPMODE = 2: uniform mesh mode
   10 10 1
/
for 2D materials and 
&kpoint
  2  # KPMODE = 2: uniform mesh mode
   10 1 1
/
for 1D material. As you know, kmesh dominates memory and computing time.
Thanks a lot!

**Comment by ttadano** [comment]
I believe they are already possible. However, the tetrahedron method ``ISMEAR = -1`` for 1D- and 2D-mesh is not available, so please use either ``ISMEAR = 0`` or ``ISMEAR = 1``.

**Comment by zhibingao** [comment]
Got it! Thanks for your kind help!
