### ISSUE TITLE
fatal error: niggli_wrapper.h: No such file or directory

### ISSUE THREAD

**Issue by nim-hrkn** [ttadano/alamode#115]
I use a52c85e572a95466bf1805720ff8fc7a9c5b5009. 
Fatal erorr occured in 'make -j'. 
What is niggli_wrapper.h?  

[ 86%] Building C object anphon/CMakeFiles/anphon.dir/__/external/niggli.c.o
In file included from /home/kino/miniconda3/include/boost/math/special_functions/detail/round_fwd.hpp:11,
                 from /home/kino/miniconda3/include/boost/math/special_functions/math_fwd.hpp:29,
                 from /home/kino/miniconda3/include/boost/math/special_functions/erf.hpp:13,
                 from /home/kino/kit/alamode/anphon/ewald.cpp:27:
/home/kino/miniconda3/include/boost/math/tools/config.hpp:23:6: warning: #warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)" [-Wcpp]
   23 | #    warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"
      |      ^~~~~~~
/home/kino/kit/alamode/anphon/kpoint.cpp:28:10: fatal error: niggli_wrapper.h: No such file or directory
   28 | #include "niggli_wrapper.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by ttadano** [comment]
Sorry, that file was missing in the previous commit. I've just added it.

**Comment by nim-hrkn** [comment]
Thank you. The programs are successfully made.
