### ISSUE TITLE
Anharmonic IFCs

### ISSUE THREAD

**Issue by chunweizhu** [ttadano/alamode#149]
Dear Tadano,

I have just come across alamode, and you mentioned, `Anharmonic force constants up to sixth-order were calculated by applying the compressive sensing approach to the training datasets generated with AIMD + random displacements.` I have no idea about "the training datasets generated with AIMD + random displacements." How can I obtain the structure of random displacements? How can I determine if the structures I generate are sufficient and reasonable? Additionally, how can I verify the reliability of the final Anharmonic force constants? Could you please provide me with some actionable guidance? 
Thank you.

**Comment by m-a-saleh** [comment]
Please refer to these tutorials:

[BaTiO3: Anharmonic interatomic force constants (IFCs)](https://alamode.readthedocs.io/en/latest/tutorial_pages/bto_ifc.html)

[Si : Anharmonic interatomic force constants (IFCs)](https://alamode.readthedocs.io/en/latest/tutorial_pages/silicon_ifc.html)

**Comment by chunweizhu** [comment]
Dear @m-a-saleh,
Thank you for your help!
