### ISSUE TITLE
`np.int` was a deprecated alias 

### ISSUE THREAD

**Issue by nim-hrkn** [ttadano/alamode#167]
I use numpy 1.26.3.

tools/interface/LAMMPS.py use np.int. It doesn't work. 
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.

**Comment by ttadano** [comment]
Thank you for letting me know this. I've fixed it.
