### ISSUE TITLE
Segmentation fault (core dumped) with the new Intel compilers

### ISSUE THREAD

**Issue by m-a-saleh** [ttadano/alamode#175]
Intel has now abandoned support of the classic C/C++ compilers (`mpiicc` & `mpiicpc`) in favor of the new compilers (`mpiicx` & `mpiicpx`). When I compile alamode with these compilers (from oneAPI 2024), I get Segmentation fault (core dumped) error even for the simple example of Si when trying to estimate force constants by fitting.

Things used to work correctly with the classical versions of the compilers

**Comment by ttadano** [comment]
Hi. 

I've quickly tested alamode v.1.5.0 with the new Intel compilers (Intel LLVM) + OpenMPI. 

The build was successful, and the example calculations went well. 

I used the following versions of the compilers and OpenMPI.

**Compilers**
```
mpicxx --version
Intel(R) oneAPI DPC++/C++ Compiler 2023.0.0 (2023.0.0.20221201)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/local/intel/oneapi/compiler/2023.0.0/linux/bin-llvm
Configuration file: /home/local/intel/oneapi/compiler/2023.0.0/linux/bin-llvm/../bin/icpx.cfg
```

**OpenMPI**
```
ldd anphon
libmpi.so.40 => /home/local/ap/openmpi/4.1.5-oneapi-2023.0.0/lib/libmpi.so.40 (0x00007f8a39e9d000)
...
```

**Comment by m-a-saleh** [comment]
I used the 2024 version. Now I reverted to the 2023 version with the classical compilers and alamode compiles well
