### ISSUE TITLE
ERROR about running the code of displace.py

### ISSUE THREAD

**Issue by Guancred** [ttadano/alamode#180]
Hi,  I run the displace.py by "python ~/alamode-1.1.0/tools/displace.py --VASP POSCAR -md vasprun.xml -e 1001:6000:50 --random --mag 0.04 --prefix disp_aimd+random_", while the error occurred as shown in the following:

"Usage: displace.py [options] file.pattern_HARMONIC file.pattern_ANHARM3 ... 
       file.pattern_* can be generated by 'alm' with MODE = suggest.

displace.py: error: no such option: -m"

Thank you very much!

**Comment by ttadano** [comment]
Please upgrade alamode to the latest version (1.5.0).

**Comment by Guancred** [comment]
> Please upgrade alamode to the latest version (1.5.0).

Hi, thank you for your replay,

i have tried to installed  the latest alamode by "make -j" in the folder of alm, while the error occurred:

icpc  -O2 -xHOST -qopenmp -std=c++11 -I../include -I/lustre/home/acct-umjzhh/umjzhh-3/include -I/lustre/home/acct-umjzhh/umjzhh-3/software/spglib-1.16.0/include -c fcs.cpp
icpc  -O2 -xHOST -qopenmp -std=c++11 -I../include -I/lustre/home/acct-umjzhh/umjzhh-3/include -I/lustre/home/acct-umjzhh/umjzhh-3/software/spglib-1.16.0/include -c symmetry.cpp
icpc  -O2 -xHOST -qopenmp -std=c++11 -I../include -I/lustre/home/acct-umjzhh/umjzhh-3/include -I/lustre/home/acct-umjzhh/umjzhh-3/software/spglib-1.16.0/include -c cluster.cpp
icpc  -O2 -xHOST -qopenmp -std=c++11 -I../include -I/lustre/home/acct-umjzhh/umjzhh-3/include -I/lustre/home/acct-umjzhh/umjzhh-3/software/spglib-1.16.0/include -c input_setter.cpp
icpc  -O2 -xHOST -qopenmp -std=c++11 -I../include -I/lustre/home/acct-umjzhh/umjzhh-3/include -I/lustre/home/acct-umjzhh/umjzhh-3/software/spglib-1.16.0/include -c optimize.cpp
icpc  -O2 -xHOST -qopenmp -std=c++11 -I../include -I/lustre/home/acct-umjzhh/umjzhh-3/include -I/lustre/home/acct-umjzhh/umjzhh-3/software/spglib-1.16.0/include -c writer.cpp
icpc  -O2 -xHOST -qopenmp -std=c++11 -I../include -I/lustre/home/acct-umjzhh/umjzhh-3/include -I/lustre/home/acct-umjzhh/umjzhh-3/software/spglib-1.16.0/include -c alm.cpp
icpc  -O2 -xHOST -qopenmp -std=c++11 -I../include -I/lustre/home/acct-umjzhh/umjzhh-3/include -I/lustre/home/acct-umjzhh/umjzhh-3/software/spglib-1.16.0/include -c patterndisp.cpp
icpc: error #10106: Fatal error in /lustre/opt/cascadelake/linux-rhel8-skylake_avx512/gcc-8.5.0/intel-oneapi-compilers-2021.4.0-5lwmbv2hynurl3dz6ewqpbqoqjmrfavz/compiler/2021.4.0/linux/bin/intel64/../../bin/intel64/mcpcom, terminated by kill signal
compilation aborted for patterndisp.cpp (code 1)
make: *** [Makefile:26: patterndisp.o] Error 1
make: *** Waiting for unfinished jobs....
icpc: error #10106: Fatal error in /lustre/opt/cascadelake/linux-rhel8-skylake_avx512/gcc-8.5.0/intel-oneapi-compilers-2021.4.0-5lwmbv2hynurl3dz6ewqpbqoqjmrfavz/compiler/2021.4.0/linux/bin/intel64/../../bin/intel64/mcpcom, terminated by kill signal
compilation aborted for optimize.cpp (code 1)
make: *** [Makefile:26: optimize.o] Error 1

Could you give me some suggestions that how to solve it?

**Comment by ttadano** [comment]
Hi. 

It's difficult for me to identify the reason of the compilation error. 

If you do not know how to fix it yourself, I suggest that you try the CMake option with conda environment. https://alamode.readthedocs.io/en/latest/install.html

**Comment by Guancred** [comment]
> Hi.
> 
> It's difficult for me to identify the reason of the compilation error.
> 
> If you do not know how to fix it yourself, I suggest that you try the CMake option with conda environment. https://alamode.readthedocs.io/en/latest/install.html

Thank you very much, the code worked well.
And i want to know whether the force constant (such as cBTO222.fcs in the example) can be convert into the format of dynaphopy?

**Comment by ttadano** [comment]
I don't know the format of dynaphopy, but probably not convertible for that code.
