### ISSUE TITLE
Atomic numbers limit?

### ISSUE THREAD

**Issue by suan12** [ttadano/alamode#2]
When I was running the program (python displace.py --VASP=POSCAR.orig --mag=0.02 si222.pattern_HARMONIC), an error occurred as belows:

Number of unique displacement patterns =  13
Traceback (most recent call last):
  File "displace.py", line 1123, in <module>
    nat, aa_inv)
  File "displace.py", line 992, in gen_displacement
    disp[atom][i] += displace[i + 1] * disp_mag
IndexError: index 80 is out of bounds for axis 0 with size 28

Q: Is there atomic numbers limit in alamode? Looking forward to your answer....

**Comment by ttadano** [comment]
This error can occur when the crystal structures (including the supercell size) for alm and POSCAR.orig are inconsistent. Please check if the POSCAR.orig file correctly contains the relaxed structure of the employed supercell.

**Comment by suan12** [comment]
Think you.
