### ISSUE TITLE
Displace.py error: list assignment index out of range

### ISSUE THREAD

**Issue by VedantBang** [ttadano/alamode#39]
Hi! I am attempting to calculate thermal parameters using Alamode and Quantum Espresso, for a certain supercell with 96 atoms.
I was able to generate the pattern_HARMONIC file using `alm`. But I am unable to generate the displaced configurations.

OS: Ubuntu 20.04

Command:
```
 python3 path_to_displace.py --QE=cell.pw.in --mag=0.01 -pf pattern_file
```

Error:
```
 File "......displace.py", line 293, in <module>
    codeobj.load_initial_structure(file_original)
 File ".........alamode/tools/interface/QE.py", line 69, in load_initial_structure
    self._set_system_info()
 File ".........alamode/tools/interface/QE.py", line 351, in _set_system_info
    self._celldm[1] = float(entrylist[i + 2])
 IndexError: list assignment index out of range
```

Seems like an issue with displace.py. Could someone help me out here?
Attaching the relevant input files for reference (as txt files).
alm input file: [inpalm.txt](https://github.com/ttadano/alamode/files/6946967/inpalm.txt)
QE input file: [cell.pw.txt](https://github.com/ttadano/alamode/files/6946981/cell.pw.txt)
Do tell me if you require the pattern file.

Thank you!

**Comment by ttadano** [comment]
Thanks for the report. There was a minor bug in the QE parser and I've fixed it. Please ``git clone`` the develop branch and use it. By the way, for the ``&position`` field of ALM, please use fractional coordinates instead of Cartesian coordinate.

**Comment by VedantBang** [comment]
Alright I shall do that, thank you!
