### ISSUE TITLE
Iterative solver of the BTE

### ISSUE THREAD

**Issue by dingzhiwei007** [ttadano/alamode#4]
Is that possible to include the iterative solver of the BTE

**Comment by ttadano** [comment]
An iterative solver of the BTE is not available in the current version of ALAMODE. We are trying to implement an iterative or direct solver in ALAMODE, but we need more time to finish it. If you have a good knowledge of an iterative algorithm and linear algebra, I think you can implement it by yourself.

I hope this answers your question.
Thank you
