### ISSUE TITLE
Missing parameters in tutorial for displace.py

### ISSUE THREAD

**Issue by tawe141** [ttadano/alamode#43]
In the tutorial here: https://alamode.readthedocs.io/en/latest/tutorial.html

`python displace.py` calls should have `-pf` prior to giving the name of the pattern file. For instance, 

`$ python displace.py --VASP=POSCAR.orig --mag=0.01 -pf si222.pattern_HARMONIC`

**Comment by ttadano** [comment]
Thank you for spotting the errors. They are now fixed.
