### ISSUE TITLE
ERROR in findsym_spglib

### ISSUE THREAD

**Issue by yxf0125** [ttadano/alamode#45]
Dear Mr./Mrs. Ttadano,

I meet an error when I get displacement patterns by alm.

----------------------------------------------------------------------------------------
SYMMETRY
=======

ERROR in findsym_spglib MESSAGE: Error occurred in spg_get_multiplicity
----------------------------------------------------------------------------------------

I am referring to the example of silicon.

Here is my alm.in file.

--------------------------------------------------------------------------------------------------
&general
  PREFIX = motes
  MODE = suggest
  NAT = 60; NKD = 3
  KD = Mo Te S
  PRINTSYM=0
/

&interaction
  NORDER = 1  # 1: harmonic, 2: cubic, ..
/

&cell
  6.013760784368251 # factor in Bohr unit
  1.000000   0.000000   0.000000  
 -0.500000   0.866025   0.000000 
  0.000000   0.000000   4.801947
/

&cutoff 
  Mo-Mo  None
  Mo-Te  None
  Mo-S  None
  Te-Te  None
  S-S  None
  Te-S None
/

&position
    1  0.000000000         0.000000000         0.742371398
    1  0.000000020         1.000000041         0.742371398
    1  0.000000041         2.000000082         0.742371398
...( These are all atomic coordinates, but I've replaced them with ellipses for simplicity. )
/

----------------------------------------------------------------------------------------------------

I am a beginner at alamode. Could you help me? Thank you very much!

**Comment by ttadano** [comment]
Hi,

Could you provide us with the input file so that I can reproduce this error? Thanks.

**Comment by yxf0125** [comment]
ok, no problem.

-----------------------------------------------------------------------------------------------------------
&general
  PREFIX = motes
  MODE = suggest
  NAT = 60; NKD = 3
  KD = Mo Te S
  PRINTSYM=0
/

&interaction
  NORDER = 1  # 1: harmonic, 2: cubic, ..
/

&cell
  6.013760784368251 # factor in Bohr unit
  1.000000   0.000000   0.000000  
 -3.000000   5.196150   0.000000 
  0.000000   0.000000   4.801947
/

&cutoff 
  Mo-Mo  None
  Mo-Te  None
  Mo-S  None
  Te-Te  None
  S-S  None
  Te-S None
/

&position
    1  0.000000000         0.000000000         0.742371398
    1  0.000000020         1.000000041         0.742371398
    1  0.000000041         2.000000082         0.742371398
    1  0.000000073         3.000000292         0.742371398
    1  0.000000082         4.000000164         0.742371398
    1  0.000000091         5.000000036         0.742371398
    1  0.000000145         6.000000584         0.742371398
    1  1.000000000         0.000000000         0.742371398
    1  1.000000020         1.000000041         0.742371398
    1  1.000000041         2.000000082         0.742371398
    1  1.000000073         3.000000292         0.742371398
    1  1.000000082         4.000000164         0.742371398
    1  1.000000091         5.000000036         0.742371398
    1  1.000000145         6.000000584         0.742371398
    2  0.666666673         0.333333347         0.859542744
    2  0.666666694         1.333333388         0.859542744
    2  0.666666714         2.333333429         0.859542744
    2  0.666666831         3.333333808         0.859542744
    2  0.666666767         4.333333680         0.859542744
    2  0.666666776         5.333333552         0.859542744
    2 -0.333333347        -0.666666694         0.859542744
    2 -0.333333327         0.333333347         0.859542744
    2 -0.333333379         1.333333388         0.859542744
    2 -0.333333359         2.333333429         0.859542744
    2 -0.333333389         3.333333808         0.859542744
    2 -0.333333380         4.333333680         0.859542744
    2 -0.333333371         5.333333552         0.859542744
    2 -0.333333023         6.333334099         0.859542744
    2  0.666666830         6.333334099         0.859542744
    2  0.666666653        -0.666666694         0.859542744
    2  1.666666747         0.333333347         0.859542744
    2  1.666666694         1.333333388         0.859542744
    2  1.666666714         2.333333429         0.859542744
    2  1.666666831         3.333333808         0.859542744
    2  1.666666840         4.333333680         0.859542744
    2  1.666666849         5.333333552         0.859542744
    2  1.666666977         6.333334099         0.859542744
    3  0.666666673         0.333333347         0.637235871
    3  0.666666694         1.333333388         0.637235871
    3  0.666666714         2.333333429         0.637235871
    3  0.666666831         3.333333808         0.637235871
    3  0.666666767         4.333333680         0.637235871
    3  0.666666776         5.333333552         0.637235871
    3 -0.333333347        -0.666666694         0.637235871
    3 -0.333333327         0.333333347         0.637235871
    3 -0.333333379         1.333333388         0.637235871
    3 -0.333333359         2.333333429         0.637235871
    3 -0.333333389         3.333333808         0.637235871
    3 -0.333333380         4.333333680         0.637235871
    3 -0.333333371         5.333333552         0.637235871
    3 -0.333333023         6.333334099         0.637235871
    3  0.666666830         6.333334099         0.637235871
    3  0.666666653        -0.666666694         0.637235871
    3  1.666666747         0.333333347         0.637235871
    3  1.666666694         1.333333388         0.637235871
    3  1.666666714         2.333333429         0.637235871
    3  1.666666831         3.333333808         0.637235871
    3  1.666666840         4.333333680         0.637235871
    3  1.666666849         5.333333552         0.637235871
    3  1.666666977         6.333334099         0.637235871
/

---------------------------------------------------------------------------------------------------------

Here is a full code.

In fact, I want to ger the results of harmonic interatomic force constants (IFCs) in ALAMODE. 
ps: I have calculated the displacement data and force data by QE.

**Comment by ttadano** [comment]
Hi,

For the &position field, please list the **fractional coordinates** of atoms in the supercell. The component of the fractional coordinates should be in the range of 0 <= xf < 1. 
All atoms outside this range are automatically moved back to the supercell.

**Comment by yxf0125** [comment]
> Hi,
> 
> For the &position field, please list the **fractional coordinates** of atoms in the supercell. The component of the fractional coordinates should be in the range of 0 <= xf < 1. All atoms outside this range are automatically moved back to the supercell.

Ok, I see. Thank you very much.
