### ISSUE TITLE
states length of Dos

### ISSUE THREAD

**Issue by bbuenim** [ttadano/alamode#55]
Hi

dos.log shows the states until 3000 cm^-1
 
bout xxx.dos shows just until about 900 cm^-1

I would like to get dos in the whole range until 3000 cm^-1

Can I set the printed data length of dos?

**Comment by ttadano** [comment]
Hi,

Please change ``EMAX``. (https://alamode.readthedocs.io/en/latest/anphondir/inputanphon.html#anphon-emin)
