### ISSUE TITLE
Si Tutorial typo

### ISSUE THREAD

**Issue by nim-hrkn** [ttadano/alamode#57]
The first step of Si tutorial  using Quantum Espresso should be

&general
MODE = ***suggest***

in https://alamode.readthedocs.io/en/latest/tutorial.html#tutorial-si-step1.
But, now it is MODE = opt, which requests the DFSET file.

In my understanding, the flowchart is 
si_alm.in -> [1. alm, mode=suggest] -> si222.pattern_HARMONIC -> [2. displace.py]  -> disp${num}.pw.in -> [3. pw.x] ->  disp${num}.pw.out -> [4. extract.py] -> DFSET_harmonic -> [5. alm, mode=top] -> si222.fcs and si222.xml
in https://alamode.readthedocs.io/en/latest/tutorial.html#label-tutorial-01.

**Comment by ttadano** [comment]
Thank you for bringing this error to my attention. The typo has been fixed.
