### ISSUE TITLE
MPI+OpenMP hybrid parallelization

### ISSUE THREAD

**Issue by ybC007** [ttadano/alamode#72]
Hi! I use MPI + OpenMP hybrid parallelization to calculate the thermal conductivity on several nodes. But I found that only the CPU of the first node is running while CPU of other nodes are not running.
![screenshot](https://user-images.githubusercontent.com/55368735/165422449-cd0e28b2-68de-4dea-a8bd-d68abf468efb.jpg)
![screenshot](https://user-images.githubusercontent.com/55368735/165422563-96fa4591-9417-4e0f-9ea7-501cddd34fb4.jpg)

**Comment by ttadano** [comment]
It not clear if the issue is related to alamode. Did you see this issue only with alamode?

**Comment by ttadano** [comment]
Close this issue. Reopen it when necessary.
